#!/bin/bash -ex
#
# script/cibuild
# ObjectiveGit
#
# Executes the build and runs tests for macOS.
#
# Dependent tools & scripts:
# - script/bootstrap
# - [xcodebuild](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html)
#
# Environment Variables:
# - SCHEME: specifies which Xcode scheme to build. Set to:
#   - ObjectiveGit Mac

if [ -z "$SCHEME" ]; then
  echo "The SCHEME environment variable is empty. Please set this to:"
  echo "- ObjectiveGit Mac"
  exit 1
fi

##
## Configuration Variables
##

set -o pipefail
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
XCWORKSPACE="ObjectiveGitFramework.xcworkspace"
XCODE_OPTIONS=(RUN_CLANG_STATIC_ANALYZER=NO ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO)

##
## Build Process
##

echo "*** Bootstrapping..."
"$SCRIPT_DIR/bootstrap"

echo "*** Building and testing $SCHEME..."
echo

xcodebuild -workspace "$XCWORKSPACE" \
  -scheme "$SCHEME" \
  "${XCODE_OPTIONS[@]}" \
  build test
