#!/bin/bash -ex

#
# clean_externals
# ObjectiveGit
#
# Removes the outputs from the various static library targets.
# Necessary when switching architectures as Xcode does not clean
# these for you.
#

libraries=(
    External/libgit2-mac.a
    External/build
)

rm -vrf "${libraries[@]}"
